pub mod analysis;
pub mod env;
mod env_watcher;
pub mod error;
pub mod exporter;
pub mod history;
pub mod importer;
pub mod path;
pub mod profile_manager;
pub mod project_config;
pub mod project_manager;
pub mod snapshot;
pub mod snapshot_manager;

pub use analysis::{Analyzer, PathAnalyzer, ValidationResult};
pub use env::{EnvVar, EnvVarManager, EnvVarSource};
pub use env_watcher::{ChangeEvent, ChangeType, ConflictStrategy, EnvWatcher, SyncMode, WatchConfig};
pub use error::EnvxError;
pub use exporter::{ExportFormat, Exporter};
pub use history::{History, HistoryEntry};
pub use importer::{ImportFormat, Importer};
pub use path::PathManager;
pub use profile_manager::ProfileManager;
pub use project_config::{ProjectConfig, RequiredVar};
pub use project_manager::{ProjectManager, ValidationReport};
pub use snapshot::{Profile, ProfileVar, Snapshot};
pub use snapshot_manager::SnapshotManager;
